project_id = "huotykitdtnycwpnnaup"

[functions.scalepad-proxy]
verify_jwt = false

[functions.app-feedback]
verify_jwt = false

[functions.lcm-data-reset-cron]
verify_jwt = false
[functions.user-vault]
verify_jwt = false
